#!/usr/bin/env python3
# Copyright (c) 2024 The mlkem-native project authors
# SPDX-License-Identifier: Apache-2.0

import subprocess
import argparse
import logging
import glob
import sys
import os
import re

def patchup_disasm(asm):
    asm = asm.split('\n')
    indentation = 8

    def decode_label(asm_line):
        r = re.search(r'^\s*[0-9a-fA-F]+\s*<([a-zA-Z0-9_]+)>:\s*$', asm_line)
        if r is None:
            return None
        return r.group(1)

    def make_label(lbl):
        return lbl + ":"

    # Find first label
    for i, l in enumerate(asm):
        if decode_label(l) is not None:
            break

    asm = asm[i+1:]
    def gen(asm):
        for l in asm:
            if l.strip() == "":
                yield ""
                continue
            lbl = decode_label(l)
            # Re-format labels as assembly labels
            if lbl is not None:
                yield make_label(lbl)
                continue
            # Drop comments
            l = l.split(';')[0]
            # Re-format references to labels
            # Those are assumed to have the form `0xDEADBEEF <label>`
            l = re.sub(r'(0x)?[0-9a-fA-F]+\s+<(?P<label>[a-zA-Z0-9_]+)>', r'\g<label>', l)
            # Drop address and byte code from line
            d = re.search('^\s*[0-9a-fA-F]+:\s+([0-9a-fA-F][0-9a-fA-F][ ]*)+\s+(?P<inst>.*)$', l)
            if d is None:
                raise Exception(f"The following does not seem to be an assembly line of the expected format `ADDRESS: BYTECODE INSTRUCTION`:\n\"{l}\"")
            yield ' ' * indentation + d.group("inst")

    return list(gen(asm))

def find_header_footer(asm, filename):
    header_end_marker = "simpasm: header-end"
    footer_start_marker = "simpasm: footer-start"

    # Extract header
    header_end = None
    for i, l in enumerate(asm):
        if header_end_marker in l:
            header_end = i
            break
    if header_end is None:
        raise Exception(f"Could not find header-end marker {header_end_marker} in {filename}")
    header = asm[:header_end]

    # Extract footer
    footer_start = None
    for i, l in enumerate(asm):
        if footer_start_marker in l:
            footer_start = i
            break
    if footer_start is None:
        raise Exception(f"Could not find footer-start marker {footer_start_marker} in {filename}")
    footer = asm[footer_start+1:]

    body = asm[header_end+1:footer_start]

    return header, body, footer

def find_globals(asm):
    global_symbols = []
    for l in asm:
        r = re.search('^\s*\.global\s+(.*)$', l)
        if r is None:
            continue
        global_symbols.append(r.group(1))
    return global_symbols

# Converts `#if ...` statements into `#if 1` in header to avoid having
# to specify various `-D...` in the CFLAGS. The original header will be
# reinstated in the final assembly, so the output is subject to the same
# guards as the input.
def drop_if_from_header(header):
    header_new = []
    i = 0
    while i < len(header):
        l = header[i]
        if not l.strip().startswith("#if"):
            header_new.append(l)
            i += 1
            continue
        header_new.append("#if 1")
        while i < len(header) and header[i].endswith("\\"):
            i += 1
        i += 1

    return header_new

def simplify(logger, args, asm_input, asm_output=None):

    if asm_output is None:
        asm_output = asm_input

    # Load input assembly
    with open(asm_input, "r") as f:
        orig_asm = f.read().split('\n')

    if args.preserve_header_footer is True:
        header, body, footer = find_header_footer(orig_asm, asm_input)
    else:
        header, body, footer = [], orig_asm, []

    # Compile assembly file
    if args.cflags is not None:
        cflags = args.cflags.split(' ')
    else:
        cflags = []

    tmp_objfile = asm_input + ".o"

    cmd = [args.cc, "-c", "-x", "assembler-with-cpp"] + cflags + ["-o", tmp_objfile, "-"]
    logger.debug(f"Assembling {asm_input} ...")
    logger.debug(f"Command: {' '.join(cmd)}")
    body_raw = '\n'.join(drop_if_from_header(header) + body + footer).encode()
    r = subprocess.run(cmd, capture_output=True, input=body_raw)
    if r.returncode != 0:
        logger.error(f"Failed to assemble {asm_input}, error code {r.returncode}.")
        logger.error(f"Command: {' '.join(cmd)}")
        logger.error(r.stderr.decode())
        exit(1)

    syms = find_globals(orig_asm)
    if len(syms) != 1:
        logger.error(f"Expected exactly one global symbol in {asm_input}, but found {syms}")
        exit(1)
    sym = syms[0]

    # Check that there is exactly one global symbol at location 0
    cmd = [args.nm, "--extern-only", tmp_objfile]
    logger.debug(f"Extracting symbols from temporary object file {tmp_objfile} ...")
    logger.debug(f"Command: {' '.join(cmd)}")
    r = subprocess.run(cmd, capture_output=True)
    if r.returncode != 0:
        logger.error(f"Failed to call `nm` on temporary object file, error code {r.returncode}.")
        logger.error(f"Command: {' '.join(cmd)}")
        logger.error(r.stderr.decode())
        exit(1)
    nm_output = r.stdout.decode().split('\n')
    nm_output = list(filter(lambda s: s.strip() != "", nm_output))
    if len(nm_output) != 1:
        logger.error(f"Found only one .global annotation in {asm_input}, but multiple external symbols in object file -- should not happen?")
        exit(1)
    sym_addr = int(nm_output[0].split(' ')[0])
    if sym_addr != 0:
        logger.error(f"Global sym {sym} not at address 0 (instead at address {hex(sym_addr)}) -- please reorder the assembly to start with the global function symbol")
        exit(1)

    cmd = [args.objdump, "--disassemble", tmp_objfile]
    logger.debug(f"Disassembling temporary object file {tmp_objfile} ...")
    logger.debug(f"Command: {' '.join(cmd)}")
    r = subprocess.run(cmd, capture_output=True)
    if r.returncode != 0:
        logger.error(f"Failed to disassemble temporary object file, error code {r.returncode}.")
        logger.error(f"Command: {' '.join(cmd)}")
        logger.error(r.stderr.decode())
        exit(1)
    disasm = r.stdout.decode()

    logger.debug("Patching up disassembly ...")
    simplified = patchup_disasm(disasm)

    autogen_header = [
        "",
        "/*",
        f" * WARNING: This file is auto-derived from {asm_input} using scripts/simpasm.",
        " *          Do not modify it directly.",
        " */",
        "",
        f".global {sym}",
        "",
        ".text",
        ".balign 4",
        f"{sym}:",
        ""
    ]

    simplified = header + autogen_header + simplified + footer

    with open(asm_output, "w+") as f:
        f.write('\n'.join(simplified))

    logger.info(f"Simplified {asm_input} -> {asm_output}")

def _main():
    parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    parser.add_argument("-d", "--directory", type=str, help="Input assembly file")
    parser.add_argument("-i", "--input", type=str, help="Input assembly file")
    parser.add_argument("-o", "--output", type=str, help="Output assembly file")
    parser.add_argument("-p", "--preserve-header-footer", default=False, action="store_true")
    parser.add_argument("-v", "--verbose", default=False, action="store_true")
    parser.add_argument("--cc", type=str, default="gcc")
    parser.add_argument("--nm", type=str, default="nm")
    parser.add_argument("--objdump", type=str, default="objdump")
    parser.add_argument("--cflags", type=str)

    args = parser.parse_args()

    logging.basicConfig(
        stream=sys.stdout, format="%(name)s: %(message)s"
    )

    logger = logging.getLogger("simpasm")
    if args.verbose is True:
        logger.setLevel(logging.DEBUG)
    else:
        logger.setLevel(logging.INFO)

    if args.input is not None:
        simplify(logger, args, args.input, args.output)
    if args.directory is not None:
        # Simplify all files in directory
        asm_files = glob.glob(args.directory + "/*.S")
        for f in asm_files:
            simplify(logger, args, f)

if __name__ == "__main__":
    _main()
